python deblur.py \
    --path './testsets/barbara/' \
    --bs 1 \
    --kernel_size 15 \
    --kernel_sigma 1 \
    --sigma 25 \
    --iteration 150000 \
    --lr 1e-4 \
    --test_frequency 1000 \
    --num_prediction 100 \
    --log_path './logs/deblur/log_barbara.txt' \
    --device 'cuda:0'